name: CI

on:
  push:
    branches:
      - features/**
      - hotfix/**
    paths:
      - projects/ng-azure-maps/**
  pull_request:
    branches:
      - develop
      - main
    paths:
      - projects/ng-azure-maps/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: Build
      run: npm run build ng-azure-maps

